language: cpp

os:
  - linux
  - osx

dist: trusty
sudo: required

compiler:
  - clang
  - gcc

env:
  - CONFIG=Release
  - CONFIG=Release TESTS_CXX_STD=17
  #- CONFIG=Debug

notifications:
 email:
   on_success: change
   on_failure: always

install:
  - g++ --version
  - cmake --version
  - git clone https://github.com/HowardHinnant/date
  - cd date
  - git checkout tags/v2.4
  - cd ..

before_script:
   - mkdir build
   - cd build
   - if [[ "$CONFIG" = "Debug" && "$TRAVIS_OS_NAME" = "linux" ]]; then
         cp -r ../scripts/ . &&
         cp -r ../test_scripts/ . &&
         sudo apt-get install python-pyparsing;
     fi
   - if [[ "$CXX" = "g++" && "$CONFIG" = "Debug" && "$TRAVIS_OS_NAME" = "linux" ]]; then export CXXFLAGS="--coverage"; fi
   - cmake .. -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_PREFIX_PATH=$PWD/../date

script:
   - if [[ -n "$TESTS_CXX_STD" ]]; then
         ARGS="-DSQLPP11_TESTS_CXX_STD=$TESTS_CXX_STD"
     fi
   - cmake --build . --config $CONFIG $ARGS
   - ctest --output-on-failure

after_script:
  - ../coveralls
