TOTAL SQL GIBBERISH HERE
CREATETABLE tab_foo
(gdfgdsf
	delta varchar(255,
	_epsilon bigint,
	`omega` double
);

CREATE TABLE tab_bar

	alpha bigint AUTO_INCREMENT,
	. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PRULL,
	delta int
)

